name: Merge Dev to Main

on:
  push:
    branches:
      - dev

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: 'main'
          fetch-depth: '0'

      - name: Merge dev branch
        run: |
          git merge origin/dev --no-edit

      - name: Configure Git
        run: |
          git config user.name JinWoo_Lee
          git config user.email dlwlsdn201@naver.com

      - name: Push changes to main branch
        uses: ad-m/github-push-action@master
        with:
          branch: main
          github_token: ${{ secrets.ACCESS_TOKEN }}
